server:
  servlet :
    context-path : /monavocat/v1
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monavocat
    username: admin
    password: admin
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    ma.pfe: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR

jwt:
  secret: SSLDSLD334534